export const categories = [
  { id: 'love', label: 'LOVE', color: '#ff2266', glow: '#ff006699' },
  { id: 'career', label: 'CAREER', color: '#00ffff', glow: '#00ffff99' },
  { id: 'wealth', label: 'WEALTH', color: '#ffcc00', glow: '#ffcc0099' },
  { id: 'health', label: 'HEALTH', color: '#00ff88', glow: '#00ff8899' },
  { id: 'destiny', label: 'DESTINY', color: '#cc66ff', glow: '#cc66ff99' },
  { id: 'mystery', label: 'MYSTERY', color: '#ff6600', glow: '#ff660099' },
]

const wisdom = {
  love: [
    "THE HEART YOU SEEK\nALREADY KNOWS\nYOUR NAME.",
    "LOVE BLOOMS WHERE\nFEAR DARES NOT\nLINGER.",
    "TWO SOULS ONCE\nLOST SHALL FIND\nEACH OTHER\nIN THE STATIC.",
    "THE ONE YOU\nTHINK ABOUT\nAT 3AM —\nTHEY THINK\nOF YOU TOO.",
    "GUARD YOUR HEART,\nBUT DO NOT\nBURY IT.\nLET IT BREATHE.",
    "A LOVE LETTER\nUNSENT IS A\nSTORY UNFINISHED.",
    "KISSES GIVEN FREELY\nARE WORTH MORE\nTHAN PROMISES\nKEPT IN CAGES.",
    "THE NEXT CHAPTER\nOF YOUR LOVE STORY\nBEGINS WITH A\nSINGLE BRAVE WORD.",
    "DO NOT CONFUSE\nFAMILIARITY\nWITH LOVE.\nCHOOSE WISELY.",
    "WHAT YOU LOVE\nMOST REVEALS\nWHO YOU TRULY ARE.",
  ],
  career: [
    "THE OPPORTUNITY\nYOU DISMISSED\nWAS ACTUALLY\nYOUR CALLING.",
    "BUILD SOMETHING\nWORTHY OF YOUR\nMIDNIGHT HOURS.",
    "EVERY EXPERT\nWAS ONCE A\nBEGINNER WHO\nDID NOT QUIT.",
    "YOUR NEXT LEVEL\nDEMANDS A\nDIFFERENT VERSION\nOF YOU.",
    "DO THE WORK\nNOBODY SEES.\nEVENTUALLY\nEVERYONE WILL.",
    "THE ROLE YOU\nWERE BORN TO PLAY\nHAS NOT BEEN\nINVENTED YET.",
    "SUCCESS LEAVES\nCLUES. FOLLOW\nTHE BREADCRUMBS.",
    "A GREAT IDEA\nUNEXECUTED IS\nJUST A DREAM.\nSTART TODAY.",
    "YOUR REPUTATION\nIS THE CURRENCY\nTHAT NEVER\nDEPRECIATES.",
    "MASTER YOUR CRAFT\nAND THE WORLD\nWILL COME\nKNOCKING.",
  ],
  wealth: [
    "RICHES FLOW TO\nTHOSE WHO KNOW\nWHEN TO HOLD\nAND WHEN TO FOLD.",
    "THE BEST INVESTMENT\nYOU WILL EVER MAKE\nIS IN YOUR\nOWN MIND.",
    "ABUNDANCE IS\nA MINDSET BEFORE\nIT BECOMES\nA BANK BALANCE.",
    "SPEND ON\nEXPERIENCES.\nTHEY COMPOUND\nFOREVER.",
    "A FORTUNE BEGINS\nWITH A SINGLE\nWISE DECISION\nMADE TODAY.",
    "DO NOT CHASE\nMONEY. BUILD\nSOMETHING MONEY\nCHASES.",
    "THE UNIVERSE\nFAVORS THE\nGENEROUS GIVER.",
    "HIDDEN WEALTH\nAWAITS. LOOK\nWHERE OTHERS\nHAVE NOT.",
    "PATIENCE IS THE\nSECRET WEAPON\nOF EVERY\nWEALTHY SOUL.",
    "SMALL ACTS OF\nFINANCIAL DISCIPLINE\nCREATE MASSIVE\nFREEDOM.",
  ],
  health: [
    "YOUR BODY IS\nA TEMPLE. TREAT\nIT LIKE THE\nSACRED PLACE IT IS.",
    "REST IS NOT\nWEAKNESS.\nIT IS THE\nFOUNDATION\nOF STRENGTH.",
    "LISTEN TO WHAT\nYOUR BODY\nWHISPERS BEFORE\nIT SCREAMS.",
    "MOVEMENT IS\nMEDICINE.\nTAKE YOUR\nDAILY DOSE.",
    "THE MIND HEALS\nFASTER WHEN\nTHE BODY IS\nKIND TO ITSELF.",
    "SLEEP REPAIRS\nMORE THAN\nYOU KNOW.\nHONOR IT.",
    "WHAT YOU EAT\nIN PRIVATE\nYOU WEAR\nIN PUBLIC.",
    "VITALITY IS\nYOUR BIRTHRIGHT.\nCLAIM IT.",
    "BREATHE DEEPLY.\nSTRESS DISSOLVES\nIN OXYGEN.",
    "A WALK OUTSIDE\nWILL SOLVE MORE\nTHAN A SCROLL\nTHROUGH DESPAIR.",
  ],
  destiny: [
    "THE PATH YOU\nFEAR MOST IS\nTHE ONE LEADING\nTO YOUR GREATNESS.",
    "YOUR DESTINY\nIS NOT WRITTEN\nIN STARS ALONE —\nIT IS WRITTEN\nIN YOUR CHOICES.",
    "THE UNIVERSE\nHAS BEEN\nARRANGING THIS\nMOMENT SINCE\nYOU WERE BORN.",
    "TRUST THE DELAY.\nYOUR TIMING IS\nDIVINE, NOT\nLATE.",
    "WHAT FEELS LIKE\nAN ENDING IS\nSIMPLY A DOOR\nCHANGING SHAPE.",
    "YOU ARE EXACTLY\nWHERE YOU NEED\nTO BE. BREATHE.",
    "YOUR FUTURE SELF\nIS CHEERING\nYOU FORWARD\nRIGHT NOW.",
    "EVERY DETOUR\nIS PART OF\nTHE ROUTE.",
    "COINCIDENCES ARE\nDESTINY IN\nDISGUISE.",
    "THE STARS ALIGNED\nTHE DAY YOU\nDECIDED TO\nBECOME YOURSELF.",
  ],
  mystery: [
    "NOT ALL DOORS\nARE MEANT TO\nBE OPENED.\nSOME ARE\nMEANT TO\nBE WONDERED AT.",
    "THE ANSWER YOU\nSEEK IS HIDING\nBEHIND THE\nQUESTION YOU\nFEAR TO ASK.",
    "REALITY IS\nTHINNER THAN\nIT APPEARS.\nLOOK SIDEWAYS.",
    "SOMETHING ANCIENT\nSTIRS IN YOUR\nBLOOD. DO NOT\nIGNORE THE\nCALLING.",
    "SECRETS KEPT\nTOO LONG\nBECOME CHAINS.\nSPEAK YOUR TRUTH.",
    "THE SHADOW SELF\nHOLDS THE KEY\nTO YOUR NEXT\nEVOLUTION.",
    "BETWEEN WORLDS\nYOU WANDER.\nCHOOSE ONE\nTO INHABIT FULLY.",
    "EVERYTHING YOU\nHAVE LOST\nSTILL EXISTS\nIN ANOTHER FORM.",
    "LOOK INTO THE\nDARKNESS WITHOUT\nBLINKING. YOUR\nPOWER LIVES\nTHERE.",
    "THE MACHINE\nSEES ALL.\nEVEN WHAT YOU\nHIDE FROM\nYOURSELF.",
  ],
}

export function getWisdom(categoryId) {
  const messages = wisdom[categoryId] || wisdom.mystery
  const index = Math.floor(Math.random() * messages.length)
  return messages[index]
}

export function getAllWisdom() {
  return wisdom
}
