// Gaming-framed wisdom for the Oracle Machine
// Each entry: { r: reading (body), p: prophecy (short punchy line) }

const wisdom = {
  love: [
    { r: "Your party is stronger when you choose teammates who buff your spirit — not ones who drain your mana just to feel powerful.", p: "Choose allies who heal, not ones who harm." },
    { r: "The NPC you keep replaying the same dialogue with is holding you back from the main quest.", p: "Close the loop. Move on." },
    { r: "Every save point is a chance to forgive the last version of yourself who loved unwisely.", p: "Reload with softer eyes." },
    { r: "Love is not a boss to defeat. It is a co-op mode — and the controller only works if you both hold it.", p: "Play together, not against." },
    { r: "The heart you are searching for is not a hidden easter egg. It appears in plain sight when you stop grinding.", p: "Slow down. They're already here." },
    { r: "Be honest early, even when honesty costs XP. A shared truth unlocks the endgame.", p: "Speak before it is too late." },
    { r: "The friend who answers at 3 AM is worth more than a hundred online acquaintances farming likes.", p: "Guard the ones who show up." },
    { r: "You cannot patch someone else's bugs with your own energy. They must open their own console.", p: "Let them fix their own code." },
    { r: "Crushes are cutscenes. Relationships are gameplay. Do not mistake the trailer for the full experience.", p: "Watch what they do, not what they promise." },
    { r: "Sometimes the quest reward is learning you deserved a better questline all along.", p: "You were never the side-character." },
    { r: "When someone shows you their true stats early, believe the numbers. Do not wait for a respec.", p: "Trust the first honest save file." },
    { r: "A relationship built only on rare loot drops will end the moment the drop rate changes.", p: "Build on presence, not prizes." },
    { r: "Flirt like it's multiplayer, not a speedrun. Let the conversation breathe.", p: "Pace matters more than combos." },
    { r: "Heartbreak is a tutorial. Painful, mandatory, and it teaches you things the main game never could.", p: "Graduate. Do not replay it." },
    { r: "The right person will not require you to glitch through walls to reach them.", p: "If it needs cheats, it is not the path." },
  ],
  quests: [
    { r: "The side quest you keep putting off is where the real XP lives. Accept it tonight.", p: "Take the detour." },
    { r: "You are not stuck. You are at a checkpoint, catching your breath before the next boss.", p: "Rest is part of the grind." },
    { r: "Level up slower than you think you should. Rushed builds collapse under pressure.", p: "Strong foundations beat fast runs." },
    { r: "The quest giver you are ignoring — the inner voice — has the best reward in the whole map.", p: "Listen to the quiet one." },
    { r: "Your inventory is full of old gear. Sell what no longer serves you. Make room for better drops.", p: "Let go to pick up." },
    { r: "Every grind ends. Every grind teaches. Neither ending nor teaching happens if you quit mid-dungeon.", p: "Finish one dungeon fully." },
    { r: "Stop comparing your chapter 3 build to someone else's endgame gear.", p: "Play your own save file." },
    { r: "The shortcut you are looking for is called consistency. It is boring. It always works.", p: "Show up again tomorrow." },
    { r: "You do not need more tools. You need to master the three in your hotbar.", p: "Depth beats collection." },
    { r: "The project you started and hid in a drawer is still a valid save. Load it.", p: "Continue the story." },
    { r: "Ask for help. Even solo runs have healers waiting nearby.", p: "Pride locks the best doors." },
    { r: "That fear you feel before the attempt? It is the loading screen, not the game.", p: "Press start anyway." },
    { r: "Small daily quests compound. Ignore the ones who chase only legendary drops.", p: "Steady XP wins the server." },
    { r: "Write down your quest log. Unmeasured dreams are just fog in the map.", p: "Pin your goals somewhere visible." },
    { r: "Your skill tree has branches you have not explored. Respec if you must.", p: "Try the unknown path." },
  ],
  boss: [
    { r: "The boss you are avoiding is the one with the best loot. That's why it hits so hard.", p: "Face it. The reward is real." },
    { r: "A failure is just a phase-change. The boss is not unbeatable — your strategy is incomplete.", p: "Study the pattern. Try again." },
    { r: "Every hard encounter has a tell. Stop panicking long enough to see it.", p: "Watch before you swing." },
    { r: "The worst fight in your life is the one where you forgot to heal between hits.", p: "Refill before the next round." },
    { r: "If the boss always wins, it is not a boss — it is an environment. Adapt.", p: "Change the arena." },
    { r: "Rage-quitting is a cooldown, not a defeat. Come back with a new build.", p: "Log back in." },
    { r: "You do not need to one-shot this. Chip damage wins long wars.", p: "Consistent small hits." },
    { r: "The boss inside your head has the highest HP pool. Start chipping today.", p: "Inner fights matter more." },
    { r: "Rubber-duck the problem. Explain the encounter out loud. Half the fight disappears.", p: "Speak it to solve it." },
    { r: "Not every fight is yours to enter. Some arenas are traps.", p: "Walk away from bait." },
    { r: "The enemy you feared turns out to be a mirror. Most bosses are.", p: "Know yourself first." },
    { r: "Stop farming the tutorial slimes. Go find something that can actually kill you.", p: "Scale up." },
    { r: "Gear check before you enter the raid. You are under-equipped.", p: "Prepare. Then commit." },
    { r: "A failure at level 30 teaches more than a victory at level 5.", p: "Lose bigger. Learn faster." },
    { r: "Cheese the boss without shame. Creative strategies are still strategies.", p: "Style points do not matter." },
  ],
  destiny: [
    { r: "You are not behind. You are playing a longer campaign with more branching endings.", p: "Your timeline is yours alone." },
    { r: "Destiny is the save file you keep making — one small choice at a time, one day at a time.", p: "You are writing it now." },
    { r: "The ending screen is still far away. Do not spoil your own game by refreshing the forums.", p: "Stay present in the playthrough." },
    { r: "The character you are becoming is more interesting than the one you started with.", p: "Growth is the real reward." },
    { r: "Fate is a recommended build, not a forced class. Respec freely.", p: "You can change class anytime." },
    { r: "Your calling is whispering through the cutscenes you keep skipping.", p: "Watch the ones you ignore." },
    { r: "The long game rewards those who log in, not those who dream of logging in.", p: "Show up. Every day." },
    { r: "You will not unlock your true ending by speed-running someone else's life.", p: "Pace is personal." },
    { r: "Every fork in the road is a save. You can load an earlier one, but you cannot delete the XP you earned.", p: "Experience compounds." },
    { r: "The quest you are meant for has been patched into the world silently. Keep exploring.", p: "Wander with intent." },
    { r: "Destiny is less a script and more a physics engine. Push. Things move.", p: "Act, and the world responds." },
    { r: "You are the protagonist of exactly one story. Treat it accordingly.", p: "Play your main character." },
    { r: "Final bosses fall to preparation built over many quiet hours.", p: "Prepare when no one is watching." },
    { r: "The ending you fear is less likely than the ending you are quietly building.", p: "Trust what you are stacking." },
    { r: "The long game needs short days. Go to sleep.", p: "Rest is part of destiny." },
  ],
};

export default wisdom;
